name: Continuous integration
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# GitHub Actions usage is FREE for both public repositories and self-hosted runners.
# We can use it to build our project and do some automated builds and in future quality tests.
# https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions

jobs:

  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # checkout project
      - uses: actions/checkout@v3

      # setup go
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.17'

      # build PR
      - name: Build translations
        working-directory: utils
        run: |
          go run .

      # check for unwanted differences from commit
      - name: Check for unwanted changes
        run: |
          changes=$(git diff | wc -l)
          if [[ $changes -gt 0 ]]; then
            git status
            git diff --color
            /bin/false
          fi

      # update translation progress
      - name: Update translation progress document
        if: github.repository == 'ReactiveDrop/reactivedrop_translations' && github.ref == 'refs/heads/master' && github.event_name == 'push'
        working-directory: utils
        run: |
          go run . -markdown > ../PROGRESS.md
      
      - name: Commit translation progress document
        if: github.repository == 'ReactiveDrop/reactivedrop_translations' && github.ref == 'refs/heads/master' && github.event_name == 'push'
        uses: EndBug/add-and-commit@v9
        with:
          message: '[CI] update translation progress'
          default_author: github_actions
          add: 'PROGRESS.md'
